server:
  port: 8110
spring:
  application:
    name: guli-edu
  profiles:
    active: dev
logging:
  level:
#    root: info
    com.atguigu.guli.service.edu.controller.admin.AdminTeacherController: debug
    com.atguigu.guli.service.edu.feign.OssClient: debug
#  datasource:
#    url: jdbc:mysql://192.168.6.100:3306/guli_edu?serverTimezone=GMT%2B8
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.6.100:8848
#  redis:
#    host: 192.168.6.100
#    port: 6379
#  rabbitmq:
#    host: 192.168.6.100
#    port: 5672
#    username: admin
#    password: root
#    virtual-host: /guli
#    listener:
#      type: simple # 使用接收请求的线程进行ack 不使用额外的线程池来处理
#      simple:
#        acknowledge-mode: manual
#        prefetch: 5
#        concurrency: 5
##      direct:

##        acknowledge-mode: manual  # 手动ack：消息消费后需要手动确认消费
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  mapper-locations: classpath*:com/atguigu/guli/service/edu/mapper/xml/*.xml

#  type-aliases-package: com.atguigu.guli.service.edu.entity
#ribbon:
#  MaxAutoRetries: 0 # 同一实例最大重试次数，不包括首次调用，默认0
#  MaxAutoRetriesNextServer: 1 # 重试其他实例的最大重试次数，不包括首次所选的server，默认1
#  ConnectTimeout: 5000 #连接建立的超时时长，默认1秒
#  ReadTimeout: 5000 #处理请求的超时时间，默认为1秒

#feign:
#  sentinel:
#    enabled: true   # 启用feign对sentinel的支持。本质就是sentinel使用动态代理 代理feign客户端
