server:
  port: 8170
spring:
  application:
    name: guli-trade
  profiles:
    active: dev
#logging:
#  level:
#    root: info
#wx:
#  pay:
#    appid: wxf913bfa3a2c7eeeb
#    mchid: 1543338551   # 商户号
#    partnerKey: atguigu3b0kn9g5vAtGuifHQH7X8rKCL   # 秘钥：加签验签使用
#    notifyUrl: http://5wc9n8g3ykp1.ngrok.xiaomiqiu123.top/api/trade/wx/callback   # 支付成功的回调地址
#  datasource:
#    url: jdbc:mysql://192.168.6.100:3306/guli_trade?serverTimezone=GMT%2B8
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8

#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.6.100
#  redis:
#    host: 192.168.6.100
#    port: 6379
#  rabbitmq:
#    host: 192.168.6.100
#    port: 5672
#    username: admin
#    password: root
#    virtual-host: /guli
#    publisher-confirm-type: simple
#    publisher-returns: true

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  mapper-locations: classpath*:com/atguigu/guli/service/trade/mapper/xml/*.xml
#  type-aliases-package: com.atguigu.guli.service.trade.entity

#ribbon:
#  MaxAutoRetries: 0 # 同一实例最大重试次数，不包括首次调用，默认0
#  MaxAutoRetriesNextServer: 1 # 重试其他实例的最大重试次数，不包括首次所选的server，默认1
#  ConnectTimeout: 5000 #连接建立的超时时长，默认1秒
#  ReadTimeout: 5000 #处理请求的超时时间，默认为1秒

#feign:
#  sentinel:
#    enabled: true   # 启用feign对sentinel的支持。本质就是sentinel使用动态代理 代理feign客户端