spring:
  application:
    name: guli-sms
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    # 如果不配置 logback-spring.xml中的  dev的日志配置不能生效
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB   # 一次请求单个表单项上传的文件大小限制
      max-request-size: 100MB  # 一次请求多个表单项上传文件总大小限制
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.6.100:8848
  redis:
    host: 192.168.6.100
    port: 6379

logging:
  level:
    root: info

server:
  port: 8150

aliyun:
  sms:
    host: "http://dingxin.market.alicloudapi.com"
    path: "/dx/sendSms"
    method: "POST"
    appcode: "9ba6170a6a6546c4a19b6c7a6c428e1c"
    tplId: "TP1711063"
